In [1]:
from tropycal import tracks

In [2]:
from HurricaneGridBase import HurricaneGridBase
hgb = HurricaneGridBase(10, 25, -80, -55)
print(hgb.markov_entries[0])

--> Starting to read in HURDAT2 data
--> Completed reading in HURDAT2 data (2.18 seconds)
((10, -80), 'N')

In [4]:
print((hgb.markov_chain.shape))

1248

In [2]:
basin = tracks.TrackDataset(basin='north_atlantic',source='hurdat',include_btk=False)

--> Starting to read in HURDAT2 data
--> Completed reading in HURDAT2 data (2.42 seconds)

In [4]:
print(basin.get_storm(("Ian", 2016)).to_dataframe().head())

                 time  extra_obs special type   lat   lon  vmax  mslp  \
0 2016-09-12 00:00:00          0           LO  20.0 -48.5    35  1007
1 2016-09-12 06:00:00          0           TS  20.5 -49.3    35  1007
2 2016-09-12 12:00:00          0           TS  21.2 -50.2    35  1006
3 2016-09-12 18:00:00          0           TS  22.2 -50.6    35  1003
4 2016-09-13 00:00:00          0           TS  23.0 -51.2    35  1000

        wmo_basin
0  north_atlantic
1  north_atlantic
2  north_atlantic
3  north_atlantic
4  north_atlantic

In [3]:
print(basin)

<tropycal.tracks.Dataset>
Dataset Summary:
    Basin:             north_atlantic
    Source:            hurdat
    Number of storms:  1973
    Maximum wind:      165 knots (Allen 1980)
    Minimum pressure:  882 hPa (Wilma 2005)
    Year range:        1851 â€” 2023

In [4]:
from HurricaneGridBase import HurricaneGridBase
hgb = HurricaneGridBase(10, 25, -80, -55)
bboxes = hgb.bboxes
bbox = bboxes[0]
print(bbox)

--> Starting to read in HURDAT2 data
--> Completed reading in HURDAT2 data (2.15 seconds)
[(10, -80), (11, -80), (11, -79), (10, -79)]

In [5]:
analogs = basin.analogs_from_shape(bbox)

--> Starting to interpolate storms
--> Completed interpolating storms (12.67 seconds)

In [6]:
print(analogs)

['AL061862', 'AL061898', 'AL041905', 'AL091961', 'AL291969', 'AL021981', 'AL141985', 'AL031993', 'AL162016']

In [7]:
import pandas
df = pandas.DataFrame()
for analog in analogs:
    storm = basin.get_storm(analog).to_dataframe()
    print(storm)

                  time  extra_obs special type   lat   lon  vmax  mslp  \
0  1862-11-22 00:00:00          0           TS  10.5 -79.5    60   NaN
1  1862-11-22 06:00:00          0           TS  10.5 -79.5    60   NaN
2  1862-11-22 12:00:00          0           TS  10.5 -79.5    60   NaN
3  1862-11-22 18:00:00          0           TS  10.5 -79.5    60   NaN
4  1862-11-23 00:00:00          0           TS  10.5 -79.5    60   NaN
5  1862-11-23 06:00:00          0           TS  10.5 -79.5    60   NaN
6  1862-11-23 12:00:00          0           TS  10.5 -79.5    60   NaN
7  1862-11-23 18:00:00          0           TS  10.5 -79.5    60   NaN
8  1862-11-24 00:00:00          0           TS  10.5 -79.5    60   NaN
9  1862-11-24 06:00:00          0           TS  10.5 -79.5    60   NaN
10 1862-11-24 12:00:00          0           TS  10.5 -79.6    50   NaN
11 1862-11-24 18:00:00          0           TS  10.5 -79.7    50   NaN
12 1862-11-25 00:00:00          0           TS  10.5 -79.8    40   NaN
13 1862-11-25 06:00:00          0           TS  10.5 -80.0    40   NaN

         wmo_basin
0   north_atlantic
1   north_atlantic
2   north_atlantic
3   north_atlantic
4   north_atlantic
5   north_atlantic
6   north_atlantic
7   north_atlantic
8   north_atlantic
9   north_atlantic
10  north_atlantic
11  north_atlantic
12  north_atlantic
13  north_atlantic
                  time  extra_obs special type   lat   lon  vmax  mslp  \
0  1898-09-20 12:00:00          0           TS  11.0 -79.8    50   NaN
1  1898-09-20 18:00:00          0           TS  12.1 -80.6    50   NaN
2  1898-09-21 00:00:00          0           TS  13.1 -81.3    50   NaN
3  1898-09-21 06:00:00          0           TS  14.0 -82.0    50   NaN
4  1898-09-21 12:00:00          0           TS  14.8 -82.6    50   NaN
5  1898-09-21 18:00:00          0           TS  15.4 -83.1    50   NaN
6  1898-09-22 00:00:00          0           TS  16.1 -83.5    50   NaN
7  1898-09-22 06:00:00          0           TS  16.7 -84.0    50   NaN
8  1898-09-22 12:00:00          0           TS  17.3 -84.5    50   NaN
9  1898-09-22 18:00:00          0           TS  18.0 -85.1    50   NaN
10 1898-09-23 00:00:00          0           TS  18.7 -85.7    50   NaN
11 1898-09-23 06:00:00          0           TS  19.4 -86.3    50   NaN
12 1898-09-23 12:00:00          0           TS  20.0 -86.9    50   NaN
13 1898-09-23 18:00:00          0           TS  20.5 -87.5    40   NaN
14 1898-09-24 00:00:00          0           TS  21.0 -88.1    35   NaN
15 1898-09-24 06:00:00          0           TS  21.4 -88.6    35   NaN
16 1898-09-24 12:00:00          0           TS  21.8 -89.2    40   NaN
17 1898-09-24 18:00:00          0           TS  22.2 -89.7    40   NaN
18 1898-09-25 00:00:00          0           TS  22.5 -90.2    45   NaN
19 1898-09-25 06:00:00          0           TS  22.9 -90.7    50   NaN
20 1898-09-25 12:00:00          0           TS  23.3 -91.2    50   NaN
21 1898-09-25 18:00:00          0           TS  23.7 -91.8    50   NaN
22 1898-09-26 00:00:00          0           TS  24.1 -92.4    50   NaN
23 1898-09-26 06:00:00          0           TS  24.5 -93.1    50   NaN
24 1898-09-26 12:00:00          0           TS  25.0 -93.7    50   NaN
25 1898-09-26 18:00:00          0           TS  25.5 -94.2    50   NaN
26 1898-09-27 00:00:00          0           TS  26.1 -94.5    50   NaN
27 1898-09-27 06:00:00          0           TS  26.7 -94.7    50   NaN
28 1898-09-27 12:00:00          0           TS  27.3 -94.8    50   NaN
29 1898-09-27 18:00:00          0           TS  27.9 -94.9    50   NaN
30 1898-09-28 00:00:00          0           TS  28.6 -94.8    50   NaN
31 1898-09-28 06:00:00          0           TS  29.3 -94.7    50   NaN
32 1898-09-28 07:00:00          1       L   TS  29.4 -94.7    50   NaN
33 1898-09-28 12:00:00          0           TS  30.0 -94.5    40   NaN
34 1898-09-28 18:00:00          0           TD  30.9 -94.4    30   NaN

         wmo_basin
0   north_atlantic
1   north_atlantic
2   north_atlantic
3   north_atlantic
4   north_atlantic
5   north_atlantic
6   north_atlantic
7   north_atlantic
8   north_atlantic
9   north_atlantic
10  north_atlantic
11  north_atlantic
12  north_atlantic
13  north_atlantic
14  north_atlantic
15  north_atlantic
16  north_atlantic
17  north_atlantic
18  north_atlantic
19  north_atlantic
20  north_atlantic
21  north_atlantic
22  north_atlantic
23  north_atlantic
24  north_atlantic
25  north_atlantic
26  north_atlantic
27  north_atlantic
28  north_atlantic
29  north_atlantic
30  north_atlantic
31  north_atlantic
32  north_atlantic
33  north_atlantic
34  north_atlantic
                  time  extra_obs special type   lat   lon  vmax   mslp  \
0  1905-10-01 06:00:00          0           TD  11.0 -79.2    30    NaN
1  1905-10-01 12:00:00          0           TD  11.0 -79.0    30    NaN
2  1905-10-01 18:00:00          0           TD  11.1 -78.8    30    NaN
3  1905-10-02 00:00:00          0           TD  11.3 -78.7    30    NaN
4  1905-10-02 06:00:00          0           TD  11.5 -78.6    30    NaN
5  1905-10-02 12:00:00          0           TD  11.7 -78.5    30    NaN
6  1905-10-02 18:00:00          0           TD  11.9 -78.3    30    NaN
7  1905-10-03 00:00:00          0           TS  12.1 -78.2    35    NaN
8  1905-10-03 06:00:00          0           TS  12.4 -78.1    35    NaN
9  1905-10-03 12:00:00          0           TS  12.7 -78.0    35    NaN
10 1905-10-03 18:00:00          0           TS  13.2 -77.9    35    NaN
11 1905-10-04 00:00:00          0           TS  13.7 -77.8    40    NaN
12 1905-10-04 06:00:00          0           TS  14.1 -77.7    40    NaN
13 1905-10-04 12:00:00          0           TS  14.5 -77.5    45    NaN
14 1905-10-04 18:00:00          0           TS  15.2 -77.0    45    NaN
15 1905-10-05 00:00:00          0           TS  15.8 -76.5    50    NaN
16 1905-10-05 06:00:00          0           TS  16.3 -76.0    50    NaN
17 1905-10-05 12:00:00          0           TS  17.0 -75.5    55    NaN
18 1905-10-05 18:00:00          0           TS  18.1 -74.8    55    NaN
19 1905-10-06 00:00:00          0           TS  19.2 -74.2    60    NaN
20 1905-10-06 06:00:00          0           TS  20.2 -73.6    60    NaN
21 1905-10-06 12:00:00          0           TS  21.0 -73.0    60    NaN
22 1905-10-06 18:00:00          0           TS  22.1 -72.3    60    NaN
23 1905-10-07 00:00:00          0           TS  23.2 -71.7    60    NaN
24 1905-10-07 06:00:00          0           TS  24.3 -71.1    60    NaN
25 1905-10-07 12:00:00          0           TS  25.3 -70.5    60    NaN
26 1905-10-07 18:00:00          0           TS  26.4 -69.6    60    NaN
27 1905-10-08 00:00:00          0           HU  27.3 -68.6    65    NaN
28 1905-10-08 06:00:00          0           HU  28.1 -67.6    70    NaN
29 1905-10-08 12:00:00          0           HU  29.0 -66.5    75    NaN
30 1905-10-08 18:00:00          0           HU  30.1 -65.0    85    NaN
31 1905-10-09 00:00:00          0           HU  30.8 -63.7    95    NaN
32 1905-10-09 06:00:00          0           HU  31.7 -62.1   105    NaN
33 1905-10-09 12:00:00          0           HU  32.3 -60.5   105    NaN
34 1905-10-09 18:00:00          0           HU  32.9 -57.5   105    NaN
35 1905-10-10 00:00:00          0           HU  33.3 -54.8   105    NaN
36 1905-10-10 06:00:00          0           HU  34.0 -52.2   100    NaN
37 1905-10-10 12:00:00          0           HU  35.0 -50.0    95    NaN
38 1905-10-10 18:00:00          0           HU  36.3 -48.6    90    NaN
39 1905-10-11 00:00:00          0           HU  37.9 -47.9    85    NaN
40 1905-10-11 06:00:00          0           EX  39.6 -47.1    80    NaN
41 1905-10-11 12:00:00          0           EX  41.0 -46.0    80    NaN
42 1905-10-11 18:00:00          0           EX  42.9 -44.8    80  945.0
43 1905-10-12 00:00:00          0           EX  45.2 -45.0    75    NaN
44 1905-10-12 06:00:00          0           EX  47.0 -46.0    70    NaN
45 1905-10-12 12:00:00          0           EX  49.0 -47.5    65    NaN
46 1905-10-12 18:00:00          0           EX  50.1 -48.4    55    NaN
47 1905-10-13 00:00:00          0           EX  51.0 -49.2    45    NaN
48 1905-10-13 06:00:00          0           EX  52.1 -50.1    35    NaN
49 1905-10-13 12:00:00          0           EX  53.0 -51.0    35    NaN
50 1905-10-13 18:00:00          0           EX  54.0 -52.1    35    NaN

         wmo_basin
0   north_atlantic
1   north_atlantic
2   north_atlantic
3   north_atlantic
4   north_atlantic
5   north_atlantic
6   north_atlantic
7   north_atlantic
8   north_atlantic
9   north_atlantic
10  north_atlantic
11  north_atlantic
12  north_atlantic
13  north_atlantic
14  north_atlantic
15  north_atlantic
16  north_atlantic
17  north_atlantic
18  north_atlantic
19  north_atlantic
20  north_atlantic
21  north_atlantic
22  north_atlantic
23  north_atlantic
24  north_atlantic
25  north_atlantic
26  north_atlantic
27  north_atlantic
28  north_atlantic
29  north_atlantic
30  north_atlantic
31  north_atlantic
32  north_atlantic
33  north_atlantic
34  north_atlantic
35  north_atlantic
36  north_atlantic
37  north_atlantic
38  north_atlantic
39  north_atlantic
40  north_atlantic
41  north_atlantic
42  north_atlantic
43  north_atlantic
44  north_atlantic
45  north_atlantic
46  north_atlantic
47  north_atlantic
48  north_atlantic
49  north_atlantic
50  north_atlantic
                  time  extra_obs special type   lat   lon  vmax   mslp  \
0  1961-10-26 00:00:00          0           TD  10.5 -79.0    25    NaN
1  1961-10-26 06:00:00          0           TD  10.6 -79.5    30    NaN
2  1961-10-26 12:00:00          0           TS  10.7 -80.0    35    NaN
3  1961-10-26 18:00:00          0           TS  10.8 -80.5    35    NaN
4  1961-10-27 00:00:00          0           TS  11.0 -81.0    35    NaN
5  1961-10-27 06:00:00          0           TS  11.3 -81.5    40    NaN
6  1961-10-27 12:00:00          0           TS  11.6 -81.8    50    NaN
7  1961-10-27 18:00:00          0           TS  12.0 -81.8    60    NaN
8  1961-10-28 00:00:00          0           HU  12.4 -81.7    70    NaN
9  1961-10-28 06:00:00          0           HU  12.9 -81.7    80    NaN
10 1961-10-28 12:00:00          0           HU  13.5 -81.6    90  969.0
11 1961-10-28 18:00:00          0           HU  14.2 -81.5   105  956.0
12 1961-10-29 00:00:00          0           HU  15.0 -81.4   110  952.0
13 1961-10-29 06:00:00          0           HU  16.0 -81.2   100  960.0
14 1961-10-29 12:00:00          0           HU  16.9 -81.3   100  963.0
15 1961-10-29 18:00:00          0           HU  17.7 -81.8   100  956.0
16 1961-10-30 00:00:00          0           HU  18.1 -82.5   100  958.0
17 1961-10-30 06:00:00          0           HU  18.5 -83.6   115  942.0
18 1961-10-30 12:00:00          0           HU  18.4 -84.4   120  937.0
19 1961-10-30 18:00:00          0           HU  18.2 -85.2   135  923.0
20 1961-10-31 00:00:00          0           HU  18.0 -86.1   145  914.0
21 1961-10-31 06:00:00          0           HU  17.5 -87.2   135  920.0
22 1961-10-31 12:00:00          0       L   HU  17.1 -88.3   130  924.0
23 1961-10-31 18:00:00          0           HU  16.8 -89.3    75    NaN
24 1961-11-01 00:00:00          0           TS  16.4 -90.2    45    NaN
25 1961-11-01 06:00:00          0           TD  16.0 -91.1    30    NaN

         wmo_basin
0   north_atlantic
1   north_atlantic
2   north_atlantic
3   north_atlantic
4   north_atlantic
5   north_atlantic
6   north_atlantic
7   north_atlantic
8   north_atlantic
9   north_atlantic
10  north_atlantic
11  north_atlantic
12  north_atlantic
13  north_atlantic
14  north_atlantic
15  north_atlantic
16  north_atlantic
17  north_atlantic
18  north_atlantic
19  north_atlantic
20  north_atlantic
21  north_atlantic
22  north_atlantic
23  north_atlantic
24  north_atlantic
25  north_atlantic
                  time  extra_obs special type   lat   lon  vmax    mslp  \
0  1969-11-20 12:00:00          0           TD  11.2 -79.8    25     NaN
1  1969-11-20 18:00:00          0           TD  11.0 -79.9    30     NaN
2  1969-11-21 00:00:00          0           TS  10.8 -80.0    35  1003.0
3  1969-11-21 06:00:00          0           TS  10.6 -80.2    45     NaN
4  1969-11-21 12:00:00          0           TS  10.5 -80.5    55     NaN
5  1969-11-21 18:00:00          0           HU  10.4 -80.8    65     NaN
6  1969-11-22 00:00:00          0           HU  10.3 -81.0    75     NaN
7  1969-11-22 06:00:00          0           HU  10.3 -81.0    80     NaN
8  1969-11-22 12:00:00          0           HU  10.3 -81.0    80   979.0
9  1969-11-22 18:00:00          0           HU  10.2 -81.0    75   982.0
10 1969-11-23 00:00:00          0           HU  10.1 -81.0    70   986.0
11 1969-11-23 06:00:00          0           TS  10.0 -81.0    55     NaN
12 1969-11-23 12:00:00          0           TS   9.9 -81.0    45   999.0
13 1969-11-23 18:00:00          0           TS   9.7 -81.0    45  1000.0
14 1969-11-24 00:00:00          0           TS   9.4 -81.0    45   999.0
15 1969-11-24 06:00:00          0           TS   9.2 -81.0    45     NaN
16 1969-11-24 12:00:00          0           TS   9.0 -81.0    45  1000.0
17 1969-11-24 18:00:00          0       L   TS   8.8 -81.1    40     NaN
18 1969-11-25 00:00:00          0           TD   8.7 -81.3    30     NaN
19 1969-11-25 06:00:00          0           TD   8.6 -81.6    30     NaN
20 1969-11-25 12:00:00          0           TD   8.5 -82.0    25     NaN

         wmo_basin
0   north_atlantic
1   north_atlantic
2   north_atlantic
3   north_atlantic
4   north_atlantic
5   north_atlantic
6   north_atlantic
7   north_atlantic
8   north_atlantic
9   north_atlantic
10  north_atlantic
11  north_atlantic
12  north_atlantic
13  north_atlantic
14  north_atlantic
15  north_atlantic
16  north_atlantic
17  north_atlantic
18  north_atlantic
19  north_atlantic
20  north_atlantic
                 time  extra_obs special type   lat   lon  vmax  mslp  \
0 1981-04-19 12:00:00          0           TD  11.0 -79.0    20   NaN
1 1981-04-19 18:00:00          0           TD  11.7 -78.7    25   NaN
2 1981-04-20 00:00:00          0           TD  12.3 -78.2    25   NaN
3 1981-04-20 06:00:00          0           TD  13.0 -78.0    25   NaN
4 1981-04-20 12:00:00          0           TD  13.5 -77.5    25   NaN
5 1981-04-20 18:00:00          0           TD  14.5 -77.5    25   NaN
6 1981-04-21 00:00:00          0           TD  14.2 -78.4    25   NaN
7 1981-04-21 06:00:00          0           TD  13.4 -79.0    20   NaN
8 1981-04-21 12:00:00          0           TD  12.8 -79.6    20   NaN
9 1981-04-21 18:00:00          0           TD  12.0 -80.2    15   NaN

        wmo_basin
0  north_atlantic
1  north_atlantic
2  north_atlantic
3  north_atlantic
4  north_atlantic
5  north_atlantic
6  north_atlantic
7  north_atlantic
8  north_atlantic
9  north_atlantic
                 time  extra_obs special type   lat   lon  vmax  mslp  \
0 1985-12-07 12:00:00          0           TD  11.2 -77.0    20   NaN
1 1985-12-07 18:00:00          0           TD  11.1 -77.5    20   NaN
2 1985-12-08 00:00:00          0           TD  11.0 -77.9    25   NaN
3 1985-12-08 06:00:00          0           TD  10.9 -78.3    25   NaN
4 1985-12-08 12:00:00          0           TD  10.6 -78.8    30   NaN
5 1985-12-08 18:00:00          0           TD  10.3 -79.4    30   NaN
6 1985-12-09 00:00:00          0           TD  10.2 -79.8    30   NaN
7 1985-12-09 06:00:00          0           TD  10.0 -80.2    25   NaN
8 1985-12-09 12:00:00          0           TD   9.8 -80.5    25   NaN
9 1985-12-09 18:00:00          0           TD   9.5 -81.0    20   NaN

        wmo_basin
0  north_atlantic
1  north_atlantic
2  north_atlantic
3  north_atlantic
4  north_atlantic
5  north_atlantic
6  north_atlantic
7  north_atlantic
8  north_atlantic
9  north_atlantic
                  time  extra_obs special type   lat   lon  vmax  mslp  \
0  1993-08-04 12:00:00          0           TD  10.4 -40.3    30  1010
1  1993-08-04 18:00:00          0           TD  10.4 -41.7    30  1009
2  1993-08-05 00:00:00          0           TS  10.4 -43.4    35  1008
3  1993-08-05 06:00:00          0           TS  10.3 -45.3    40  1007
4  1993-08-05 12:00:00          0           TS  10.3 -47.3    45  1006
5  1993-08-05 18:00:00          0           TS  10.3 -49.2    45  1006
6  1993-08-06 00:00:00          0           TS  10.2 -51.0    45  1006
7  1993-08-06 06:00:00          0           TS  10.1 -52.9    50  1005
8  1993-08-06 12:00:00          0           TS  10.0 -54.9    50  1005
9  1993-08-06 18:00:00          0           TS  10.1 -56.8    50  1003
10 1993-08-07 00:00:00          0           TS  10.4 -58.6    50  1002
11 1993-08-07 06:00:00          0           TS  10.7 -60.5    50  1002
12 1993-08-07 07:00:00          1       L   TS  10.8 -60.8    50  1002
13 1993-08-07 10:00:00          1       L   TS  10.8 -61.8    50  1002
14 1993-08-07 12:00:00          0           TS  10.8 -62.4    50  1002
15 1993-08-07 18:00:00          0           TS  10.8 -64.1    45  1006
16 1993-08-08 00:00:00          0           TS  10.8 -65.7    40  1008
17 1993-08-08 06:00:00          0           TS  11.0 -67.6    40  1007
18 1993-08-08 08:00:00          1       L   TS  11.0 -68.3    40  1007
19 1993-08-08 12:00:00          0           TS  11.0 -69.7    40  1007
20 1993-08-08 18:00:00          0           TS  11.0 -71.8    40  1007
21 1993-08-09 00:00:00          0           TS  10.9 -73.8    40  1006
22 1993-08-09 06:00:00          0           TS  10.7 -75.8    35  1005
23 1993-08-09 12:00:00          0           TD  10.7 -77.8    30  1004
24 1993-08-09 18:00:00          0           TD  10.7 -79.2    30  1005
25 1993-08-10 00:00:00          0           TD  10.8 -80.3    30  1004
26 1993-08-10 06:00:00          0           TS  11.0 -81.4    35  1003
27 1993-08-10 12:00:00          0           TS  11.1 -82.6    40  1002
28 1993-08-10 17:00:00          1       L   TS  11.1 -83.8    40  1002
29 1993-08-10 18:00:00          0           TS  11.1 -84.0    35  1004
30 1993-08-11 00:00:00          0           TD  11.4 -85.0    25  1007
31 1993-08-11 06:00:00          0           TD  11.7 -85.8    20  1009
32 1993-08-11 12:00:00          0           TD  12.2 -86.8    20  1010

         wmo_basin
0   north_atlantic
1   north_atlantic
2   north_atlantic
3   north_atlantic
4   north_atlantic
5   north_atlantic
6   north_atlantic
7   north_atlantic
8   north_atlantic
9   north_atlantic
10  north_atlantic
11  north_atlantic
12  north_atlantic
13  north_atlantic
14  north_atlantic
15  north_atlantic
16  north_atlantic
17  north_atlantic
18  north_atlantic
19  north_atlantic
20  north_atlantic
21  north_atlantic
22  north_atlantic
23  north_atlantic
24  north_atlantic
25  north_atlantic
26  north_atlantic
27  north_atlantic
28  north_atlantic
29  north_atlantic
30  north_atlantic
31  north_atlantic
32  north_atlantic
                  time  extra_obs special type   lat   lon  vmax  mslp  \
0  2016-11-17 18:00:00          0           LO  12.5 -80.7    20  1006
1  2016-11-18 00:00:00          0           LO  12.3 -81.3    20  1005
2  2016-11-18 06:00:00          0           LO  11.8 -81.7    20  1005
3  2016-11-18 12:00:00          0           LO  11.4 -82.0    20  1005
4  2016-11-18 18:00:00          0           LO  11.2 -82.0    20  1005
5  2016-11-19 00:00:00          0           LO  11.1 -82.0    25  1005
6  2016-11-19 06:00:00          0           LO  11.0 -81.8    25  1005
7  2016-11-19 12:00:00          0           LO  10.9 -81.5    25  1005
8  2016-11-19 18:00:00          0           LO  10.8 -81.2    25  1005
9  2016-11-20 00:00:00          0           LO  10.7 -80.8    25  1005
10 2016-11-20 06:00:00          0           LO  10.7 -80.4    25  1005
11 2016-11-20 12:00:00          0           LO  10.9 -80.0    25  1004
12 2016-11-20 18:00:00          0           TD  11.1 -79.7    30  1002
13 2016-11-21 00:00:00          0           TD  11.3 -79.4    30  1002
14 2016-11-21 06:00:00          0           TS  11.3 -79.3    35  1002

In [8]:
observations = hgb.observations_in_bbox(bbox)
print(observations)

--> Starting to interpolate storms
--> Completed interpolating storms (14.37 seconds)
22

Seems like a rate of around 50-60 bboxes counted every minute. I think in this smaller example it there are around 375 bboxes ~7 minutes but with the full 7000 bboxes ~140 minutes (not good)

In [16]:
print(hgb.get_entry_for_lat_lon(10, -80.0))

(0, 0)